# Generated by Django 5.1.5 on 2025-01-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "permissions": [("toggle_document", "Can change status document")]
            },
        ),
    ]
