# Generated by Django 5.0.7 on 2025-02-22 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0005_status_alter_atob_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=100)),
                ("date", models.DateTimeField(blank=True)),
                ("bool", models.BooleanField(default=False)),
                ("number", models.IntegerField(default=0)),
                ("float", models.FloatField(default=0.0)),
            ],
        ),
    ]
