version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"  # SSL port
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # Configure listeners for both SSL and plaintext for internal communication
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,SSL://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,SSL://0.0.0.0:9093
      KAFKA_SSL_PROTOCOL_VERSION: TLSv1.2
      KAFKA_SSL_KEYSTORE_FILENAME: keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: keystore_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: keystore_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
      # Credential files to allow Kafka to read the keystore/truststore passwords
      KAFKA_SSL_KEYSTORE_CREDENTIALS_FILE: /etc/kafka/secrets/kafka_creds.txt
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS_FILE: /etc/kafka/secrets/kafka_creds.txt
    volumes:
      - ./certs/keystore.jks:/etc/kafka/secrets/keystore.jks
      - ./certs/truststore.jks:/etc/kafka/secrets/truststore.jks
      - ./certs/kafka_creds.txt:/etc/kafka/secrets/kafka_creds.txt
      - ./certs/keystore_creds:/etc/kafka/secrets/keystore_creds

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.2.1
    volumes:
       - ./message.json:/data/message.json
       - ./certs/truststore.jks:/etc/kafka/secrets/truststore.jks
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: password
    depends_on:
      - kafka
    command: >
      bash -c '
        echo "Waiting for Kafka to be ready..." &&
        cub kafka-ready -b kafka:9093 1 30 &&
        kafka-topics --create --topic test_topic --replication-factor 1 --partitions 1 --if-not-exists --bootstrap-server kafka:9093 &&
        kafka-console-producer --bootstrap-server kafka:9093 --topic test_topic < /data/message.json'

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9020:8080
    environment:
      AUTH_TYPE: DISABLED
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093  # Use the SSL port
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE: /etc/kafka/secrets/truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: password
    volumes:
      - ./certs/truststore.jks:/etc/kafka/secrets/truststore.jks

