"""
Django settings for authest project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import base64
from datetime import timedelta
from pathlib import Path

import requests
import json
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-71@e)c!s!y9)96libcc%d8y7jm!vc4sj4p$2*oy4&!&#q8maw5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

SHARED_APPS = [
    # 'django_tenants',  # mandatory
    'users', # you must list the app where your tenant model resides in

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    "rest_framework",
    'rest_framework_simplejwt',
    'dj_rest_auth',
    'rest_framework.authtoken',
    'mozilla_django_oidc',
]

TENANT_APPS = [
    # your tenant-specific apps
    "myapp",
]

INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]


MIDDLEWARE = [
    # 'django_tenants.middleware.main.TenantMainMiddleware',  # must be
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

# NEW 
# https://medium.com/@robertjosephk/setting-up-keycloak-in-django-with-django-allauth-cfc84fdbfee2
# https://www.linkedin.com/pulse/setting-up-keycloak-django-django-allauth-robert-joseph-kalapurackal-oy4xc/
AUTHENTICATION_BACKENDS = [
    "mozilla_django_oidc.auth.OIDCAuthenticationBackend",
    # 'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = "authest.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "authest.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django_tenants.postgresql_backend',
#         'NAME': 'authest',                      
#         'USER': 'postgres_user',
#         'PASSWORD': 'postgres_password',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "users.User"

TENANT_MODEL = "users.Client"
TENANT_DOMAIN_MODEL = "users.Domain"

# https://www.keycloak.org/getting-started/getting-started-docker
# http://localhost:8080/admin/master/console/#/authest/clients/3bd3c8ab-f87c-4a00-8e3f-70b975413839/settings
SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "keycloak",
                "name": "Keycloak",
                "client_id": "my-backend-app",
                "secret": "dKBGsoVz9ER5U4GGGk3MXoqpFHohYIpM",  # from docker Keycloak -- not prod 
                "settings": {
                    "server_url": "http://pi5:8080/realms/master/.well-known/openid-configuration",
                },
            }
        ]
    }
} 

SITE_ID = 1


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
        # "dj_rest_auth.authentication.AllAuthJWTAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# DATABASE_ROUTERS = (
#     'django_tenants.routers.TenantSyncRouter',
# )

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
}

OIDC_RP_CLIENT_ID = "my-backend-app"
OIDC_RP_CLIENT_SECRET = "dKBGsoVz9ER5U4GGGk3MXoqpFHohYIpM"
OIDC_OP_JWKS_ENDPOINT = "http://pi5:8080/realms/master/protocol/openid-connect/certs"
OIDC_OP_AUTHORIZATION_ENDPOINT = "http://pi5:8080/realms/master/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "http://pi5:8080/realms/master/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "http://pi5:8080/realms/master/protocol/openid-connect/userinfo"

# Optional settings
OIDC_CREATE_USER = True
OIDC_VERIFY_SSL = False  # Set to True in production

SIMPLE_JWT = {
    "ALGORITHM": "RS256",
    "SIGNING_KEY": None,  # We will get the public key dynamically
    "VERIFYING_KEY": None,
    "ISSUER": "http://pi5:8080/realms/master",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "sub",
    "USER_ID_CLAIM": "sub",
    "AUDIENCE": "account"
}


def get_keycloak_public_key():
    response = requests.get(OIDC_OP_JWKS_ENDPOINT)
    if response.status_code == 200:
        jwks = response.json()
        if "keys" in jwks and len(jwks["keys"]) > 0:
            key = jwks["keys"][0]  # First key in the list
            if key["kty"] == "RSA":
                # Decode "n" and "e" values
                n = int.from_bytes(base64.urlsafe_b64decode(key["n"] + "=="), "big")
                e = int.from_bytes(base64.urlsafe_b64decode(key["e"] + "=="), "big")

                # Create RSA public key
                public_key = rsa.RSAPublicNumbers(e, n).public_key(default_backend())

                # Convert to PEM format
                pem_key = public_key.public_bytes(
                    encoding=serialization.Encoding.PEM,
                    format=serialization.PublicFormat.SubjectPublicKeyInfo,
                )
                return pem_key.decode("utf-8")

    return None  # If no valid key is found

SIMPLE_JWT["VERIFYING_KEY"] = get_keycloak_public_key()


print("Django Key:", SIMPLE_JWT["VERIFYING_KEY"])

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["console"],
#             "level": "DEBUG",
#             "propagate": True,
#         },
#         "rest_framework": {
#             "handlers": ["console"],
#             "level": "DEBUG",
#             "propagate": False,
#         },
#     },
# }